GET http://127.0.0.1:5000/
Content-Type: application/json
###

POST http://127.0.0.1:5000/
Content-Type: application/json

{
    "text": "продаю велик",
    "owner": "Андрей"
}
###

DELETE http://127.0.0.1:5000/6
Content-Type: application/json
